# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ad0b1ba3cad86a21da45fd5749f0e3c8845300d2b8f718a057f7736842037037f2465fe8e27279168ed757da133fecbd94ed23724d14af24c0053073465c6e

test:
  secret_key_base: b9297296c0a8fc97a9d2c054d0fe6a23b6b285b95568295c0f620ae842b6691dcb045cd48c3f1f558c561777e6e2adedb805ded641bdf67dc8632c17646378f0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
